GET http://localhost:5000/
###
GET http://localhost:8000/
###

GET http://localhost:5000/users
###

GET http://localhost:5000/subscribe/0
###
GET http://0.0.0.0:5001/users
###

POST http://127.0.0.1:5001/register
Content-Type: application/json

{
"username": "Stefan", "password": "12345"
}

###

POST http://0.0.0.0:5001/login
Content-Type: application/json

{
"username": "Matt", "password": "12345"
}
###

POST http://0.0.0.0:5001/gameover
Authorization: abc
Content-Type: application/json

{
"username": "mike"
}
###
